@startuml
class TimedRDMSim
{
  + int getSimTime()
  + void run()
  + void runStep(int t)
}

class Effector
{
  + setMirrors(int m, int t) : Action
  + setStrategy(TopologyStrategy strategy, int t) : Action
  + setTargetLinksPerMirror(int numTargetedLinks, int t) : Action
  + timeStep(int t)
}

class Action
{
    id : int
    time : int
}

class Effect {
    + deltaActiveLinks() : int
    + deltaBandwidth() : int
    + deltaTimeToWrite() : int
    + requiredTimeSteps() : int
}

class MirrorChange {
    newMirrors : int
}

class TopologyChange {
    newStrategy : ToplogyStrategy
}

class TargetLinkChange {
    newTargetLinksPerMirror : int
}

Action <|-- MirrorChange
Action <|-- TopologyChange
Action <|-- TargetLinkChange

class Network

TimedRDMSim -> Effector
Network <- TimedRDMSim
Effector  o--> "*" Action
Action <-> Effect
Effector -[hidden]-> Effect
Network <- Action
@enduml